export const MODE_RECIPE = {
  light: {
    background: 0.995,
    foreground: 0.145,
    surface: 0.98,
    raised: 1,
    muted: 0.94,
    mutedText: 0.44,
    border: 0.82,
    input: 0.62,
    destructive: 0.54,
    conflictingDestructive: 0.43,
  },
  dark: {
    background: 0.145,
    foreground: 0.96,
    surface: 0.185,
    raised: 0.215,
    muted: 0.245,
    mutedText: 0.78,
    border: 0.34,
    input: 0.52,
    destructive: 0.637,
    conflictingDestructive: 0.68,
  },
};

export const TOKEN_ORDER = [
  "background",
  "foreground",
  "surface",
  "raised surface",
  "muted surface",
  "muted text",
  "border",
  "input border",
  "brand source",
  "primary",
  "primary hover",
  "primary active",
  "primary text",
  "primary border",
  "focus ring",
  "destructive",
  "destructive hover",
  "destructive active",
  "destructive text",
  "warning",
  "warning hover",
  "warning active",
  "warning text",
  "selection",
  "selection text",
  "disabled background",
  "disabled text",
  "disabled border",
  "popover",
  "popover text",
];

export const ROLE_CLASSIFICATION = {
  passthrough: ["brand source"],
  searched: [
    "primary border",
    "warning",
    "warning hover",
    "warning active",
    "warning text",
    "destructive hover",
    "destructive active",
    "selection",
    "selection text",
  ],
  aliases: {
    "disabled background": "muted surface",
    "disabled text": "muted text",
    "disabled border": "border",
    popover: "raised surface",
    "popover text": "foreground",
  },
  nonColorRequirements: {
    disabled: [
      "disabled attribute",
      "no pointer activation",
      "reduced emphasis",
    ],
    selection: ["selected state semantics", "shape or position cue"],
    warning: ["warning icon or label", "not color alone"],
  },
};
